### ISSUE TITLE
No release files

### ISSUE THREAD

**Issue by agile-heresy** [hyperrationaltech/stlm-helper#16]
Hey, this is a really cool set of tools, but since I am not a go developer, it took a bit to pull the code, set up the environment and build the binary. Could you add the exe as a release? It  looks like that may have been the intention based on the github workflow file. 

Thanks!

**Comment by pietersartain** [comment]
Thanks for the prompt! I've got the windows part of the ghactions building, I haven't tested the macos or linux, but we've got something there at least :) You'll find an unsigned exe in the release.
